{{- $localOpaqueSecrets := default (list) .Values.opaqueSecrets }}
{{- $globalOpaqueSecrets := default (list) .Values.global.opaqueSecrets }}
{{- range $secret := (concat $globalOpaqueSecrets $localOpaqueSecrets) -}}
apiVersion: v1
kind: Secret
metadata:
  {{- with $secret.namespace }}
  namespace: {{ $secret.namespace }}
  {{- end}}
  {{- with $secret.name}}
  name: {{ $secret.name  | lower}}
  {{- end }}
  {{- with $secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
{{- range $key, $value := $secret.data -}}
  {{ $key | quote | nindent 2 }}: {{ $value | b64enc | quote}}
{{- end }}
---
{{- end }}